chore: add provenance to all packages
LottieFiles/relottie pull request #113
Opened 2024-11-07 10:48 UTC by Aidosmf

## Description

## Type of change

- [ ]  Patch: Bug (non-breaking change which fixes an issue)
- [ ]  Minor: New feature (non-breaking change which adds functionality)
- [ ]  Major: Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] This is something we need to do.

2024-11-10 21:47 UTC, jawish requested changes

2024-11-10 21:47 UTC, jawish commented on .github/workflows/release.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}
Needs to be GITHUB_TOKEN

2024-11-10 21:47 UTC, jawish commented on .github/workflows/release.yml
> +      - name: Remove existing NPM .npmrc
Doesn't need to create or delete a .npmrc file.

2024-11-11 05:45 UTC, Aidosmf commented
@jawish done, also remove renovate, please review again

2024-11-12 02:22 UTC, jawish approved these changes

2024-11-12 04:08 UTC, merged